version: '3'
services:
  application:
    container_name: testdocker
    build: .
    ports:
    - 8080:8080
    networks:
      - fethi
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
    - 3306:3306
    container_name: mariadbtest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdocker
    networks:
      - fethi
networks:
  fethi: