spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/testdocker
    password: root
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    data: "classpath*:data.sql"
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
